### ISSUE TITLE
Some exceptions don't catch

### ISSUE THREAD

**Issue by 6aKa** [mojolicious/mojo.js#54] opened 2022-01-14 17:00 UTC
Demo application
```
/*
 * Application demonstrating the various HTTP response variants for debugging
 */
import mojo from '../lib/core.js';
import net from 'net';

const app = mojo();

app.get('/res1', ctx => {
  const client = net.createConnection({port: 8124}, () => {
    console.log('connected to server!');
  });

  return ctx.render({text: 'Hello World!'});
});

app.get('/res2', async ctx => {
  function myAsyncFunction() {
    return new Promise((resolve, reject) => {
      const client = net.createConnection({port: 8124}, () => {
        console.log('connected to server!');
        resolve(client);
      });
      client.on('error', error => {
        reject(error);
      });
    });
  }

  await myAsyncFunction();

  await ctx.render({text: 'Hello World!'});
});

app.start();
```

**Comment by kraih** [comment] 2022-01-14 17:01
I can already tell that `/res1` is not a bug, the response gets sent before the connection is created. Node should exit there. But `/res2` is a bug.

**Comment by kraih** [comment] 2022-01-14 20:13
Should be resolved with https://github.com/mojolicious/mojo.js/commit/e948ab5e84fc6731b2dadf7c65137a313bf86d33.

**Closed by kraih** 2022-01-14 20:13 UTC
Labels: bug
